[package]
name = "canonical"
version.workspace = true
edition.workspace = true

[dependencies]
canonical-compat = { path = "../canonical-compat" }
canonical-core = { path = "../canonical-core" }
once_cell = "1.21.1"

[lib]
crate-type = ["cdylib"]
