name: Build Canonical for Lean

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            lib_path: target/release/libcanonical.so
          - os: macos-latest
            lib_path: target/release/libcanonical.dylib
          - os: windows-latest
            lib_path: target/x86_64-pc-windows-gnu/release/canonical.dll

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install elan
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf |
            sh -s -- -y --default-toolchain none
          rm -f elan-init
          echo "$HOME/.elan/bin" >>"$GITHUB_PATH"

      - name: Install Lean
        shell: bash
        run: |
          elan toolchain install stable
          elan default stable

      - name: Add Lean to PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: echo "$env:USERPROFILE\.elan\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build canonical (Windows)
        if: runner.os == 'Windows'
        run: cargo build -p canonical --release --target x86_64-pc-windows-gnu

      - name: Build canonical
        if: runner.os != 'Windows'
        run: cargo build -p canonical --release

      - name: Upload built library
        uses: actions/upload-artifact@v4
        with:
          name: canonical-${{ matrix.os }}
          path: ${{ matrix.lib_path }}
